# Generated by Django 5.2.13 on 2026-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('internships', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('technical_skills_score', models.IntegerField()),
                ('hackerrank_score', models.IntegerField()),
                ('placement_status', models.CharField(blank=True, max_length=50)),
                ('prediction_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
